### ISSUE TITLE
always say EOF

### ISSUE THREAD

**Issue by Thecoolpeople** [slimtoolkit/slim#501]
Expected Behavior
=================
i tried to slim the ubuntu:20.04 image, and an own image. Both are getting Error EOF

---
Actual Behavior
=================
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/slim:1.40.0
app='slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
app='slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='slim' message='GitHub Discussions' info='https://github.com/docker-slim/docker-slim/discussions'

build --target ubuntu:20.04       **<-- this is the line I inserted in the docker container**

app='slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
app='slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='slim' message='GitHub Discussions' info='https://github.com/docker-slim/docker-slim/discussions'
cmd=build info=exec message='changing continue-after from probe to nothing because http-probe is disabled'
cmd=build info=exec message='changing continue-after to enter'
cmd=build state=started
cmd=build info=params target='ubuntu:20.04' continue.mode='enter' rt.as.user='true' keep.perms='true' tags='' target.type='image'
cmd=build state=image.inspection.start
cmd=build info=image id='sha256:1c5c8d0b973ab9d6d7742cf050beefa8ba2efb7779e09bfb1200d6192180766e' size.bytes='72785566' size.human='73 MB'
cmd=build info=image.stack index='0' name='ubuntu:20.04' id='sha256:1c5c8d0b973ab9d6d7742cf050beefa8ba2efb7779e09bfb1200d6192180766e'
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
time="2023-03-28T15:18:04Z" level=error msg="dockerutil.BuildEmptyImage: dockerapi.BuildImage() error = unexpected EOF"
time="2023-03-28T15:18:04Z" level=fatal msg="docker-slim: failure" error="unexpected EOF" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn({0x1eaeac0, 0xc00003a140})\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:28 +0x5e\ngithub.com/docker-slim/docker-slim/pkg/app/master/inspectors/container.(*Inspector).RunContainer(0xc000114b00)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/inspectors/container/container_inspector.go:422 +0x694\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.OnCommand(_, _, {_, _}, _, {_, _}, {_, _}, {0x0, ...}, ...)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/handler.go:875 +0x4186\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.glob..func1(0xc00026b280)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/cli.go:640 +0x4bb0\ngithub.com/urfave/cli/v2.(*Command).Run(0x2c82de0, 0xc000496d80)\n\tgithub.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc000509520, {0x1ec7d18?, 0xc000042020}, {0xc0002701e0, 0x5, 0x5})\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:224\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands.(*InteractiveApp).execute(0xc000495590, {0xc00068f830?, 0xc00049e030?})\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/cliprompt.go:101 +0x354\ngithub.com/c-bata/go-prompt.(*Prompt).Run(0xc000488900)\n\tgithub.com/c-bata/go-prompt@v0.2.3/prompt.go:85 +0x82d\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands.(*InteractiveApp).Run(...)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/cliprompt.go:187\ngithub.com/docker-slim/docker-slim/pkg/app/master.newCLI.func4(0xc000496a40?)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/cli.go:172 +0x50\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc000509520, {0x1ec7d18?, 0xc000042020}, {0xc00003a200, 0x1, 0x1})\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:322 +0x953\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:224\ngithub.com/docker-slim/docker-slim/pkg/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/app.go:15 +0x46\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/slim/main.go:15 +0x1aa\n" version="linux|Transformer|1.40.0|a4bb798922820523fceedb9121f5bcfdfc9f2901|2023-01-16_01:52:31AM"
`

---
Steps to Reproduce the Problem
===============================

  1. use the latest (1.40.0) and dockerizied
  2. run `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/slim:1.40.0`
  3. inside docker write `build --target ubuntu:20.04`
  4. See EOF Error

---
Specifications
=================
  - Version: 1.40.0
  - Platform: docker

**Comment by kcq** [comment]
This is an odd error... the app can't build an empty image (which is necessary before the docker volume with the sensor can be created).

Can you try setting the logging level to debug or trace to see what's going on inside: `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/slim:1.40.0 --log-level=trace build --target ubuntu:20.04` (or something like that)

**Comment by auspex** [comment]
Was there ever a resolution? I seem to be having the same problem with the same Ubuntu version

**Comment by kcq** [comment]
@auspex definitely has been addressed :-) Try using the [latest release](https://github.com/mintoolkit/mint/releases/tag/1.41.8)

**Comment by auspex** [comment]
Well, I only pulled it this morning.

**Comment by kcq** [comment]
@auspex let's confirm the version you pulled, how you installed it and where :-) Do you mind running `mint --version` to get started.

**Comment by auspex** [comment]
`mint --version` isn't relevant. It's a docker container. Since I pulled `dslim/slim:latest` a week ago, it was whatever was current then. I no longer have a copy, because afaict the problem actually occurred because I hadn't mounted the volumes that the `target` image needed, and I didn't have the time to analyze it further and create a similar volume and copy of the target image, that I could afford an unknown image to play with. Maybe another day.

**Comment by zrks** [comment]
I have the same, fails on all images I tried:
```
slim --version
mint version linux/amd64|Aurora|1.41.8-1-g4b0d7e91|4b0d7e915ef33a98a2b32ccc10c8558086b27fe4|2025-12-12_05:28:51AM
```

**Comment by kcq** [comment]
> I have the same, fails on all images I tried:
> 
> ```
> slim --version
> mint version linux/amd64|Aurora|1.41.8-1-g4b0d7e91|4b0d7e915ef33a98a2b32ccc10c8558086b27fe4|2025-12-12_05:28:51AM
> ```

Are you using the container version or are you using the CLI binaries directly? Looks like you are running on Linux... What version of Docker do you have installed?

**Comment by zrks** [comment]
> > I have the same, fails on all images I tried:
> > ```
> > slim --version
> > mint version linux/amd64|Aurora|1.41.8-1-g4b0d7e91|4b0d7e915ef33a98a2b32ccc10c8558086b27fe4|2025-12-12_05:28:51AM
> > ```
> 
> Are you using the container version or are you using the CLI binaries directly? Looks like you are running on Linux... What version of Docker do you have installed?

```
$ docker version
Client: Docker Engine - Community
 Version:           29.7.2
 API version:       1.55
 Go version:        go1.26.5
 Git commit:        a7dcaa6
 Built:             Wed Aug  5 18:28:53 2026
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.7.2
  API version:      1.55 (minimum version 1.40)
  Go version:       go1.26.5
  Git commit:       6a43e3d
  Built:            Wed Aug  5 18:28:53 2026
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.3.3
  GitCommit:        aad11006b869517fcd3009450b6f82da282e1a9b
 runc:
  Version:          1.4.3
  GitCommit:        v1.4.3-0-gbb14dabe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

using CLI binary directly
