### ISSUE TITLE
python module not found errors

### ISSUE THREAD

**Issue by Divyesh3011** [slimtoolkit/slim#546]
---
Facing Modules / package error 

2023-07-12 17:08:15 Traceback (most recent call last):
2023-07-12 17:08:15   File "/usr/local/lib/python3.8/decimal.py", line 3, in <module>
2023-07-12 17:08:15     from _decimal import *
2023-07-12 17:08:15 ModuleNotFoundError: No module named 'numbers'
2023-07-12 17:08:15 
2023-07-12 17:08:15 During handling of the above exception, another exception occurred:
2023-07-12 17:08:15 
2023-07-12 17:08:15 Traceback (most recent call last):
2023-07-12 17:08:15   File "main.py", line 2, in <module>
2023-07-12 17:08:15     from fastapi import FastAPI
2023-07-12 17:08:15   File "/usr/local/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
2023-07-12 17:08:15     from .applications import FastAPI as FastAPI
2023-07-12 17:08:15   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 3, in <module>
2023-07-12 17:08:15     from fastapi import routing
2023-07-12 17:08:15   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 20, in <module>
2023-07-12 17:08:15     from fastapi import params
2023-07-12 17:08:15   File "/usr/local/lib/python3.8/site-packages/fastapi/params.py", line 4, in <module>
2023-07-12 17:08:15     from pydantic.fields import FieldInfo, Undefined
2023-07-12 17:08:15   File "pydantic/__init__.py", line 2, in init pydantic.__init__
2023-07-12 17:08:15   File "pydantic/dataclasses.py", line 3, in init pydantic.dataclasses
2023-07-12 17:08:15     import copy
2023-07-12 17:08:15   File "pydantic/class_validators.py", line 8, in init pydantic.class_validators
2023-07-12 17:08:15   File "pydantic/errors.py", line 1, in init pydantic.errors
2023-07-12 17:08:15   File "/usr/local/lib/python3.8/decimal.py", line 8, in <module>
2023-07-12 17:08:15     from _pydecimal import *
2023-07-12 17:08:15 ModuleNotFoundError: No module named '_pydecimal'
---
Steps to Reproduce the Problem (DockerFile)
===============================
FROM python:3.8-slim-buster AS build
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \ 
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Final stage
FROM python:3.8-slim-buster
WORKDIR /app
COPY --from=build /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
COPY . .
RUN pip install --no-cache-dir -r requirements.txt fastapi==0.68.1 uvicorn==0.15.0
CMD ["bash", "azure-soc2-manager.sh"]
EXPOSE 8000

# Create preserved-paths.txt file in the final image
RUN echo "/usr/local/usr/local/lib/python3.8" > /preserved-paths.txt 

  1.  first i build the image using the above docker file 
  2.  Then i slim the image build 
  command use are 
  docker build -t soc2-test-1 .   (to build-image)
  docker-slim build --target soc2-test-11 --tag soc2-test-slim --http-probe=false
  
docker images | grep soc2

soc2-test-1                                               slim
           cf086482e0b3   About a minute ago   33.9MB
soc2-test-1                                               latest
           d3fdfab4467d   10 minutes ago       279MB
---

**Comment by kcq** [comment]
@Divyesh3011 what version of slim are you using? Also wonder why you disabled http probing: `docker-slim build --target soc2-test-11 --tag soc2-test-slim --http-probe=false`

Can you also describe what your app does and how the missing libraries are used in your app if you use them directly (e.g., pydantic)?

**Comment by Divyesh3011** [comment]
slim version linux|Transformer|1.40.2|762eea87bafc4b04fe6b0642a62534a148acdaca|2023-05-20_06:09:23AM
there is no specific reason behind disabling http probing i just found one of the eg similar to this so i  used this cmd should i modify the cmd ?
the app is part of multiple microservices which are use to scan the image for any vulnerablity
this is my requirement file
i have multiple microservices most of them use the python:3.8-slim image as base & i am getting similar module/packages error 
can you help me with a standard docker-file for python svc that would support docker-slim 
[requirement.txt](https://github.com/slimtoolkit/slim/files/12067449/requirement.txt)

**Comment by kcq** [comment]
Can you describe what your app does?

**Comment by Divyesh3011** [comment]
the app is part of multiple microservices which are use to scan the image for any vulnerablity i 
is there are way where i can specify the slim not to delete certain package like having a preserve.txt file where we keep all the required package & dependecy & tell slim to make sure all the package specified in the  preserve.txt file are present in final Image
i have multiple microservice & for different svc i get different/package depedency error so having something like preserve.txt file will help to solve the errors

Docker file 
FROM python:3.10-slim-buster
RUN  pip3 install anyio==3.5.0
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "start_server.py", "--reload","--port=8000"]

one of the depedecy-error i am facing (this dependecy is mentioned in requirement.txt file) with normal image it work but with slim image i get errors
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'anyio._backends'

**Comment by Divyesh3011** [comment]
@kcq 
Traceback (most recent call last):
  File "/app/start_server.py", line 1, in <module>
    from app.main import app
  File "/app/app/main.py", line 17, in <module>
    from .models.discovery import ScanRQ,ScanRequest
ModuleNotFoundError: No module named 'app.models.discovery'

It shows no app.models.discovery but i have checked the path it contains the file 
/app
└── app
    ├── __init__.py
    ├── main.py
    └── models
        ├── __init__.py
        └── discovery.py
