### ISSUE TITLE
Unable to run demo application

### ISSUE THREAD

**Issue by raakasf** [slimtoolkit/slim#556]
Expected Behavior
=================
Be able to run demo application

---
Actual Behavior
=================
Demo steps fail with error

---
Steps to Reproduce the Problem
===============================
 

  1. git clone https://github.com/slimtoolkit/examples.git
  2. cd examples/node_ubuntu
  3.  docker build -t my/sample-node-app .
  4. slim build my/sample-node-app

`slim build my/sample-node-app
app='slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
app='slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='slim' message='GitHub Discussions' info='https://github.com/slimtoolkit/slim/discussions'
cmd=build info=param.http.probe message='using default probe' 
cmd=build state=started
cmd=build info=params rt.as.user='true' keep.perms='true' tags='' target.type='image' target='my/sample-node-app' continue.mode='probe' 
cmd=build state=image.inspection.start
cmd=build info=image id='sha256:e176f589144b1c3a44ac0c50496399baf37e6dcd6411a0d4e8295bd16f730294' size.bytes='414788140' size.human='415 MB' 
cmd=build info=image.stack index='0' name='ubuntu:14.04' id='sha256:13b66b487594a1f2b75396013bc05d29d9f527852d96c5577cc4f187559875d0' 
cmd=build info=image.stack index='1' name='my/sample-node-app:latest' id='sha256:e176f589144b1c3a44ac0c50496399baf37e6dcd6411a0d4e8295bd16f730294' 
cmd=build info=image.exposed_ports list='1300' 
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
cmd=build info=container id='c5b8b6bd24c0ae82ae3f695690e30b6c03118572b6751dd36848f33bc8f30846' status='created' name='slimk_967928_20230801152718' 
cmd=build info=container name='slimk_967928_20230801152718' id='c5b8b6bd24c0ae82ae3f695690e30b6c03118572b6751dd36848f33bc8f30846' status='running' 
cmd=build info=container message='obtained IP address' ip='101.10.0.5' 
time="2023-08-01T11:28:27-04:00" level=error msg="channel.NewCommandClient: NewClient error = wait timeout"
time="2023-08-01T11:28:27-04:00" level=error msg="ipc.NewClient init error = wait timeout"
cmd=build info=report file='slim.report.json' 
time="2023-08-01T11:28:27-04:00" level=fatal msg="slim: failure" error="wait timeout" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn({0x1f9fa00, 0xc0003cd0f0})\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:32 +0x5e\ngithub.com/docker-slim/docker-slim/pkg/app.(*ExecutionContext).FailOn(0xc0004c2580?, {0x1f9fa00?, 0xc0003cd0f0?})\n\tgithub.com/docker-slim/docker-slim/pkg/app/execontext.go:56 +0x49\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.OnCommand(_, _, {_, _}, _, {_, _}, {_, _}, {0x0, ...}, ...)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/handler.go:1121 +0x440b\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.glob..func1(0xc0004eba80)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/cli.go:744 +0x5e90\ngithub.com/urfave/cli/v2.(*Command).Run(0x2dd7e20, 0xc0004b94c0)\n\tgithub.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc000503040, {0x1fb9118?, 0xc0000480e0}, {0xc00003e090, 0x3, 0x3})\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:224\ngithub.com/docker-slim/docker-slim/pkg/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/app.go:15 +0x46\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/slim/main.go:15 +0x18c\n" version="linux|Transformer|1.40.2|latest|latest"`

---
Specifications
=================
  - Version: 1.40.2
  - Platform: CentOS
  - Working on a corporate network that blocks access to unknown urls

This is the first time I'm using `slim`, I started with my own image by got the above error so thought maybe I could run the demo first and see if it works (it didn't).

**Comment by kcq** [comment]
thanks for opening the issue @raakasf ! investigating...

**Comment by Jeansen** [comment]
Same here when running on of the examples. There's also already a ticket in the examples repo with a similar issue from 22`. Hiere's my exectution trace:
```
Building Slim Image
docker-slim  build  dslimexamples/app-golang-ubuntu
cmd=build state=started
cmd=build info=params target.type='image' target.image='dslimexamples/app-golang-ubuntu' continue.mode='timeout' rt.as.user='true' keep.perms='true' tags='' image-build-engine='internal'
cmd=build state=image.inspection.start
cmd=build info=image id='sha256:31321daa942ad3ef4afcf585b5bd4fb9e3eba01cbc06f7238c9ee4ad026b0e4a' size.bytes='820713656' size.human='821 MB'
cmd=build info=image.stack index='0' name='dslimexamples/app-golang-ubuntu:latest' id='sha256:31321daa942ad3ef4afcf585b5bd4fb9e3eba01cbc06f7238c9ee4ad026b0e4a'
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
cmd=build info=container status='created' name='slimk_985753_20240712155547' id='de7562b0ff6013c53bdd5f099ffde7cc4b8ec03b259acfa7cbfa9eebb20a397f'
cmd=build info=container status='running' name='slimk_985753_20240712155547' id='de7562b0ff6013c53bdd5f099ffde7cc4b8ec03b259acfa7cbfa9eebb20a397f'
cmd=build info=container message='obtained IP address' ip='172.17.0.3'
cmd=build info=cmd.startmonitor status='sent'
cmd=build info=event.startmonitor.done status='received.unexpected' data='{"name":"event.monitor.start.failed","data":{"component":"monitor.runner","state":"/","errors":["insufficient permissions"]}}
'
slim: container stdout:
slim: container stderr:
time="2024-07-12T15:55:48Z" level=error msg="sensor: composite monitor - FAN failed to start running"
time="2024-07-12T15:55:48Z" level=error msg="sensor: failed to start composite monitor" error="insufficient permissions"
time="2024-07-12T15:55:48Z" level=error msg="sensor: run finished with error" error="run sensor without monitor failed: insufficient permissions"
time="2024-07-12T15:55:48Z" level=error msg="channel.Server.Start() - loop.Accept error = accept tcp [::]:65501: use of closed network connection"
time="2024-07-12T15:55:48Z" level=error msg="channel.Server.Start() - loop.Accept error = accept tcp [::]:65502: use of closed network connection"
slim: end of container logs =============
cmd=build info=report file='slim.report.json'
cmd=build info=fail.on version='linux/amd64|Transformer|1.40.11|1b271555882eacdfb4e6598d6d0552e9b9b1449b|2024-02-02_01:36:22PM'
cmd=build info=exit code='-1' version='linux/amd64|Transformer|1.40.11|1b271555882eacdfb4e6598d6d0552e9b9b1449b|2024-02-02_01:36:22PM' location='/usr/local/bin'
app='slim' message='GitHub Discussions' info='https://github.com/slimtoolkit/slim/discussions'
app='slim' message='Join the CNCF Slack channel to ask questions or to share your feedback' info='https://cloud-native.slack.com/archives/C059QP1RH1S'
app='slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
time="2024-07-12T17:55:48+02:00" level=error msg=terminating error="unexpected event type" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/slimtoolkit/slim/pkg/app.(*ExecutionContext).FailOn(0xc000151160, {0x2329020, 0x338f350})\n\tgithub.com/slimtoolkit/slim/pkg/app/execontext.go:58 +0x58\ngithub.com/slimtoolkit/slim/pkg/app/master/command/build.OnCommand(_, _, {_, _}, _, {_, _}, {_, _}, {0x0, ...}, ...)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/command/build/handler.go:1136 +0x46a5\ngithub.com/slimtoolkit/slim/pkg/app/master/command/build.glob..func1(0xc0006a8480)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/command/build/cli.go:760 +0x5d51\ngithub.com/urfave/cli/v2.(*Command).Run(0x33a7220, 0xc0006a8480, {0xc000417ca0, 0x2, 0x2})\n\tgithub.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd\ngithub.com/urfave/cli/v2.(*Command).Run(0xc000322b00, 0xc000147cc0, {0xc000050180, 0x3, 0x3})\n\tgithub.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc0001bc600, {0x23470c8?, 0x341e0a0}
```

**Comment by Jeansen** [comment]
Oh, and I am also not able to get any sort of a successful result when manually running the build command, no matter what  container image I try. It's all similar to the output above. I had hope at least the examples would work...so I could track down the error ... but unfortunately they don't.
