### ISSUE TITLE
dockerutil.BuildEmptyImage() fails with bad API version

### ISSUE THREAD

**Issue by jimcottrell** [slimtoolkit/slim#646]
I've got a CI/CD pipeline that's run occasionally when we rebuild a image and create an optimized version with Slim. Without anything having changed that I'm aware of (same Slim version, same pipeline runner), this process has started failing with:

```
dockerutil.BuildEmptyImage: dockerapi.BuildImage() error = API error (400): client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

I thought this might be related to #637, but it seems to be a separate issue, and the same thing happens whether or not I try setting `--crt-api-version`. Having updated everything to the latest versions, the problem continues. The issue seems to be specific to this environment, as a local build works.

---
Steps to Reproduce the Problem
===============================
 

1.  slim build --http-probe-off --continue-after=enter alpine

*(trivial reproduction; of course not our actual image)*

```
cmd=build state=started
cmd=build info=params target.image='alpine' continue.mode='enter' rt.as.user='true' keep.perms='true' tags='' image-build-engine='internal' target.type='image' 
cmd=build state=image.inspection.start
cmd=build info=image id='sha256:05455a08881ea9cf0e752bc48e61bbd71a34c029bb13df01e40e3e70e0d007bd' size.bytes='0' size.human='0 B' 
cmd=build info=image.stack index='0' name='alpine:latest' id='sha256:05455a08881ea9cf0e752bc48e61bbd71a34c029bb13df01e40e3e70e0d007bd' 
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
time="2024-02-26T18:12:39Z" level=error msg="dockerutil.BuildEmptyImage: dockerapi.BuildImage() error = API error (400): client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version\n / output: "
time="2024-02-26T18:12:39Z" level=fatal msg="slim: failure" error="API error (400): client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version\n" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/slimtoolkit/slim/pkg/util/errutil.FailOn({0x231e3e0, 0xc0007e62a0})\n\tgithub.com/slimtoolkit/slim/pkg/util/errutil/errutil.go:32 +0x4b\ngithub.com/slimtoolkit/slim/pkg/app/master/inspectors/container.(*Inspector).RunContainer(0xc000464b00)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/inspectors/container/container_inspector.go:430 +0x77a\ngithub.com/slimtoolkit/slim/pkg/app/master/command/build.OnCommand(_, _, {_, _}, _, {_, _}, {_, _}, {0x0, ...}, ...)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/command/build/handler.go:1132 +0x4632\[ngithub.com/slimtoolkit/slim/pkg/app/master/command/build.glob..func1(0xc0003d35c0)\n\tgithub.com/slimtoolkit/slim/pkg/app/master/command/build/cli.go:760](http://ngithub.com/slimtoolkit/slim/pkg/app/master/command/build.glob..func1(0xc0003d35c0)/n/tgithub.com/slimtoolkit/slim/pkg/app/master/command/build/cli.go:760) +0x5d51\[ngithub.com/urfave/cli/v2.(*Command](http://ngithub.com/urfave/cli/v2.(*Command)).Run(0x3396180, 0xc0000af480)\n\[tgithub.com/urfave/cli/v2@v2.3.0/command.go:163](http://tgithub.com/urfave/cli/v2@v2.3.0/command.go:163) +0x583\[ngithub.com/urfave/cli/v2.(*App](http://ngithub.com/urfave/cli/v2.(*App)).RunContext(0xc000266d00, {0x233bb88?, 0x340d500}, {0xc00012e000, 0x7, 0x7})\n\[tgithub.com/urfave/cli/v2@v2.3.0/app.go:313](http://tgithub.com/urfave/cli/v2@v2.3.0/app.go:313) +0xaa5\[ngithub.com/urfave/cli/v2.(*App](http://ngithub.com/urfave/cli/v2.(*App)).Run(...)\n\[tgithub.com/urfave/cli/v2@v2.3.0/app.go:224\ngithub.com/slimtoolkit/slim/pkg/app/master.Run()\n\tgithub.com/slimtoolkit/slim/pkg/app/master/app.go:15](http://tgithub.com/urfave/cli/v2@v2.3.0/app.go:224/ngithub.com/slimtoolkit/slim/pkg/app/master.Run()/n/tgithub.com/slimtoolkit/slim/pkg/app/master/app.go:15) +0x45\nmain.main()\n\[tgithub.com/slimtoolkit/slim/cmd/slim/main.go:15](http://tgithub.com/slimtoolkit/slim/cmd/slim/main.go:15) +0x187\n" version="linux/amd64|Transformer|1.40.11|1b271555882eacdfb4e6598d6d0552e9b9b1449b|2024-02-02_01:36:22PM"
```

---
Specifications
=================
  - Version: 1.40.11
  - Platform: linux/amd64 (self-hosted Bitbucket pipeline runner, which is configured for privileged Docker access so Slim can run)
- Output of `slim version`:
```
cmd=version info=app container='true' dsimage='false' location='/opt/atlassian/pipelines/agent/build/dist_linux' current='1.40.11' verdict='you have the latest version' cmd='version' version='linux/amd64|Transformer|1.40.11|1b271555882eacdfb4e6598d6d0552e9b9b1449b|2024-02-02_01:36:22PM' 
cmd=version info=host cmd='version' osname='Ubuntu 22.04.3 LTS' osbuild='' version='#18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024' release='6.2.0-1018-aws' sysname='Linux' 
cmd=version info=docker server.version='25.0.3' architecture='x86_64' cmd='version' name='a640edfcc04d' kernel.version='6.2.0-1018-aws' operating.system='Alpine Linux v3.19 (containerized)' ostype='linux' 
cmd=version info=dclient build.time='2024-02-06T21:13:08.000000000+00:00' git.commit='f417435' cmd='version' api.version='1.44' min.api.version='1.24' 
app='slim' message='GitHub Discussions' info='https://github.com/slimtoolkit/slim/discussions'
app='slim' message='Join the CNCF Slack channel to ask questions or to share your feedback' info='https://cloud-native.slack.com/archives/C059QP1RH1S'
app='slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
```

**Comment by kcq** [comment]
Interesting... need to investigate/repro. Either way, the next release should address this. Check back a bit later or follow me on Github or Twitter to be notified when the new release is out.

**Comment by jimcottrell** [comment]
Sounds good, thanks. I'll see how the next version works out. We're still having some build issues, but it looks like if we set a `DOCKER_API_VERSION` environment variable, we can at least get past this error.

**Comment by jimcottrell** [comment]
For reference, other versions may work (`1.44` did not), but we seem to be back in business with
```
export DOCKER_API_VERSION='1.25'
```
in our pipeline

**Comment by kcq** [comment]
@jimcottrell this might work as-is https://github.com/mintoolkit/mint/releases/tag/1.41.1 let me know if you still have problems there

**Comment by jimcottrell** [comment]
I've tried with v1.41.1 and no explicit `DOCKER_API_VERSION` and I get that same error: `client version 1.12 is too old`

**Comment by kcq** [comment]
@jimcottrell which version of Docker do you have installed? Are you on Mac or Linux? If you are on Linux are you using Docker Desktop or only Docker Engine? If you are on a Mac is it an AMD or an M1/M2? Trying to repro... more info on your environment will help

**Comment by sammcj** [comment]
Getting this on Fedora 39 with the latest stable docker-ce and slim installed.

```
slim build --target nvapi --tag slim --http-probe=false --dockerfile Dockerfile --dockerfile-context .
...
cmd=build info=build.error status='standard.image.build.error' value='API /build requires version 1.25, requested version 1.24 is insufficient'
cmd=build state=exited code=33554435 version=linux/amd64|Transformer|1.40.11|1b271555882eacdfb4e6598d6d0552e9b9b1449b|2024-02-02_01:36:22PM location=/usr/local/bin
```

```
dnf info docker-ce-26.1.1-1.fc39.x86_64
Last metadata expiration check: 4:53:24 ago on Sun 05 May 2024 09:04:18.
Installed Packages
Name         : docker-ce
Epoch        : 3
Version      : 26.1.1
Release      : 1.fc39
Architecture : x86_64
Size         : 104 M
Source       : docker-ce-26.1.1-1.fc39.src.rpm
Repository   : @System
From repo    : docker-ce-stable
Summary      : The open-source application container engine
URL          : https://www.docker.com
```

**Comment by kcq** [comment]
@sammcj do you get the same result with [this](https://github.com/mintoolkit/mint/releases/tag/1.41.1) version?

**Comment by kcq** [comment]
@sammcj will try to repro with Fedora 39

**Comment by jimcottrell** [comment]
@kcq Sorry for the delay in responding. As noted before, this is happening only on a self-hosted Bitbucket pipeline runner (linux/amd64). When I run locally, I have no issue. To make Slim work in the pipeline environment, it has to run via the `docker:dind` image.

## Host Docker

```
+ docker version
Client:
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:17:06 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:45 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.13
  GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## `docker:dind`

```
+ docker version
Client:
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:17:06 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:58 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.15
  GitCommit:        926c9586fe4a6236699318391cd44976a98e31f1
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Looking at this does seem to explain why I couldn't set it to use v1.44.

**Comment by kcq** [comment]
> @kcq Sorry for the delay in responding. As noted before, this is happening only on a self-hosted Bitbucket pipeline runner (linux/amd64). When I run locally, I have no issue. To make Slim work in the pipeline environment, it has to run via the `docker:dind` image.
> 
> ## Host Docker
> ```
> + docker version
> Client:
>  Version:           20.10.24
>  API version:       1.41
>  Go version:        go1.19.7
>  Git commit:        297e128
>  Built:             Tue Apr  4 18:17:06 2023
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> Server: Docker Engine - Community
>  Engine:
>   Version:          25.0.2
>   API version:      1.44 (minimum version 1.24)
>   Go version:       go1.21.6
>   Git commit:       fce6e0c
>   Built:            Thu Feb  1 00:23:45 2024
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          v1.7.13
>   GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8
>  runc:
>   Version:          1.1.12
>   GitCommit:        v1.1.12-0-g51d5e94
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> ## `docker:dind`
> ```
> + docker version
> Client:
>  Version:           20.10.24
>  API version:       1.41
>  Go version:        go1.19.7
>  Git commit:        297e128
>  Built:             Tue Apr  4 18:17:06 2023
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> Server: Docker Engine - Community
>  Engine:
>   Version:          26.1.3
>   API version:      1.45 (minimum version 1.24)
>   Go version:       go1.21.10
>   Git commit:       8e96db1
>   Built:            Thu May 16 08:33:58 2024
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          v1.7.15
>   GitCommit:        926c9586fe4a6236699318391cd44976a98e31f1
>  runc:
>   Version:          1.1.12
>   GitCommit:        v1.1.12-0-g51d5e94
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> Looking at this does seem to explain why I couldn't set it to use v1.44.

Running with dind in Bitbucket runners makes it more complicated because each CI/CD vendor does the dind setup in slightly different ways, which requires different ways to connect to the (correct) Docker runtime. Some environments don't expose the Docker unix socket. Other environments needs certs to connect to the Docker runtime. Some have more advanced network configurations that prevents direct container communication, so the `--sensor-ipc-mode` and `--sensor-ipc-endpoint` flags need to be used. The [`RUNNING CONTAINERIZED`](https://github.com/mintoolkit/mint?tab=readme-ov-file#running-containerized) README section covers a few examples

To troubleshoot your setup we need two things to get started:

1. How you invoke the slim command in your dind setup.
2. Your Bitbucket runner config that defines how the dind magic is configured.

**Comment by jimcottrell** [comment]
Here's a simplified version of our `bitbucket-pipelines.yml` that fails with `client version 1.12 is too old`:

```yaml
image:
  name: atlassian/default-image:4
definitions:
  services:
    privileged-docker:
      type: docker
      image:
        name: docker:dind
pipelines:
  custom:
    test:
      - step:
          runs-on:
            - linux
            - self.hosted
          name: Build Optimized Image
          services:
            - privileged-docker
          script:
            - curl https://downloads.dockerslim.com/releases/1.40.11/dist_linux.tar.gz -o slim.tar.gz
            - tar xvf slim.tar.gz
            #- export DOCKER_API_VERSION='1.25' # Temporary, see https://github.com/slimtoolkit/slim/issues/646
            - ./dist_linux/slim build --continue-after=enter alpine
```

I tried it with `--in-container=true` which didn't make any difference. What needs to be updated to point to the dind Docker runtime? Apart from this one case, I'm not very familiar with dind. The `DOCKER_HOST` environment variable exists, but I don't believe the Docker UNIX socket is present.

**Comment by schowave** [comment]
Are there any updates here? 

I am having the same problem with a gitlab pipeline and dind

**Comment by kcq** [comment]
The latest [release, 1.41.5](https://github.com/mintoolkit/mint/releases/tag/1.41.5), shouldn't have the docker API problem.

To connect to the Docker daemon it might be necessary to extract the daemon IP address from the /etc/hosts file if the environment doesn't configure DOCKER_HOST on its own properly. Here's an example for Gitlab (need to double check if it still works): `docker run -e DOCKER_HOST=tcp://$(grep docker /etc/hosts | cut -f1):2375 mintoolkit/mint slim your-docker-image-name`

Might need to use the `--sensor-ipc-mode` and `--sensor-ipc-endpoint` flags too for `dind` depending on the CI/CD vendor.

I'll repro it with Gitlab first to confirm that the setup is still ok. Then I'll try to repro with a Bitbucket setup.

**Comment by schowave** [comment]
Okay, than the installation routine should be adapted:
I installed it via:

`curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | bash -
`
and in the script, the latest version is:

`curl -sL https://api.github.com/repos/slimtoolkit/slim/releases | grep tag_name | head -n1 | cut -d'"' -f4`
`1.40.11`

**Comment by kcq** [comment]
> Okay, than the installation routine should be adapted: I installed it via:
> 
> `curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | bash - ` and in the script, the latest version is:
> 
> `curl -sL https://api.github.com/repos/slimtoolkit/slim/releases | grep tag_name | head -n1 | cut -d'"' -f4` `1.40.11`

should be this install script: https://raw.githubusercontent.com/mintoolkit/mint/master/scripts/install-mint.sh

**Comment by marcoaversanoigt** [comment]
Hello there! 
I had same problem with latest mint 1.41.7, Docker latest (27.3.1), Docker API v1.47, and the only solution was to set explicitely => DOCKER_API_VERSION=1.47

**Comment by kcq** [comment]
> Hello @kcq ! 
> I had same problem with latest mint 1.41.7, Docker latest (27.3.1), Docker API v1.47, and the only solution was to set explicitely => DOCKER_API_VERSION=1.47

What image did you try to slim or was it a different command? Do you have a repro?

**Comment by marcoaversanoigt** [comment]
> > Hello @kcq !
> > I had same problem with latest mint 1.41.7, Docker latest (27.3.1), Docker API v1.47, and the only solution was to set explicitely => DOCKER_API_VERSION=1.47
> 
> What image did you try to slim or was it a different command? Do you have a repro?

It is a custom internal image, already created.
Found just now that i'm forced to use the 'export' => 
```
export DOCKER_API_VERSION=1.47
mint slim [...]
```
or
to put the variable definition inline => 
`DOCKER_API_VERSION=1.47 mint slim [...]`

While if i do:
```
DOCKER_API_VERSION=1.47
mint slim [...]
```
It says again client API 1.12 is too old.

**Comment by kcq** [comment]
Thank you for the additional context @marcoaversanoigt ! This will help with my repro. We have the environment and the command context that should be enough. Working on the repro (hopefully can repro it without the Github workflow part :-))

**Comment by KarimABOUSSELHAM** [comment]
Hello guys.
I was running through the same issue discussed here a few days ago. I started the resolution it by reinstalling `dockerd` then I ensured that `docker slim` installed version matches with my OS/WSL distro then the famous command `slim build <image-name>` hopefully worked.

**Comment by Seluj78** [comment]
For anyone confused like me regarding the updates, version problem or whatever, `mint` is deprecated, you now need to install `mint`: https://github.com/mintoolkit/mint

**Comment by kcq** [comment]
> For anyone confused like me regarding the updates, version problem or whatever, `mint` is deprecated, you now need to install `mint`: https://github.com/mintoolkit/mint

Yes, the latest enhancements are there. There's a new release coming soon too.

**Comment by NilsMoller** [comment]
> For anyone confused like me regarding the updates, version problem or whatever, `mint` is deprecated, you now need to install `mint`: https://github.com/mintoolkit/mint

You said `mint` is deprecated twice. Did you mean to say `slim` in one of those? Which one is deprecated and which one should be used? I'm running into the same problem. `slim version` tells me the api version is `1.44` but I'm still getting this error for version `1.12` in bitbucket pipelines (not self hosted).

**Comment by kcq** [comment]
> NilsMoller

It was a typo. He meant to say slim :-) It's not really deprecated, but the current updates are in the mint releases. @NilsMoller are you using the [latest release](https://github.com/mintoolkit/mint/releases/tag/1.41.7) ? If not try using it and let me know if you are getting the same behavior. This particular API version problem has been tricky to track down / repro. The upcoming release will have a number docker client/API enhancements and also container image format handling enhancements for XRAY among other things.

**Comment by NilsMoller** [comment]
I am using the latest version (as far as i know). I will move to mint and try again. Thanks!

**Comment by NilsMoller** [comment]
I am now using Mint installed using the scripted install (as specified in the [README](https://github.com/mintoolkit/mint?tab=readme-ov-file#scripted-install)). It works locally, but in the Bitbucket pipeline it fails with the same error.
In the pipeline, the output of `mint --version` is as follows:
```
mint version linux/amd64|Aurora|1.41.7|a2a53d2348aeedf0d650d47debf477a2cad47111|2024-09-25_03:07:42PM
```

**Comment by kcq** [comment]
Thanks for the update @NilsMoller ! Good that it's functional locally. That's a useful data point for the repro. Next is for me to repro a bitbucket setup.

**Comment by klauss42** [comment]
I am confused about the different tools slim versus mint. Both look similar. Which one is maintained, which one is deprecated. There is no info in either of the repos. Could you please bring some light into the dark? And maybe add some little docs in the readme's about this? Thanks

**Comment by kcq** [comment]
@klauss42 it's a bit messy at this point in time. Sorry about that. It's partially related to the CNCF requirement to change the project name when the project was accepted into CNCF. There's more to it... I hope to make it more straight forward in the future and ideally it'll be back to one. If you'd like to chat more about the details around it let's pick a time to chat. Either way, the new enhancements and features are added in Mint.

**Comment by kcq** [comment]
> I am now using Mint installed using the scripted install both locally and in the Bitbucket pipeline (as specified in the [README](https://github.com/mintoolkit/mint?tab=readme-ov-file#scripted-install)). It works locally, but in the Bitbucket pipeline it fails with the same error as above. In the pipeline, the output of `mint --version` is as follows:
> 
> ```
> mint version linux/amd64|Aurora|1.41.7|a2a53d2348aeedf0d650d47debf477a2cad47111|2024-09-25_03:07:42PM
> ```
> 
> And the output of the command is this:
> 
> ```
> > mint --expose=26232 access-control
> 
> cmd=slim info=param.http.probe message='using default probe' 
> 
> cmd=slim state=started
> 
> cmd=slim info=cmd.input.params continue.mode='probe' rt.as.user='true' keep.perms='true' tags='' image-build-engine='internal' target.type='image' target.image='access-control' 
> 
> cmd=slim state=image.inspection.start
> 
> cmd=slim info=image id='sha256:8c0c37682eb191e8406a89a842ad5cb2568e39d81225a329945c4da44e848c91' size.bytes='0' size.human='0 B' 
> 
> cmd=slim info=image.users all='access-control' exe='access-control' 
> 
> cmd=slim info=image.stack index='0' name='access-control:latest' id='sha256:8c0c37682eb191e8406a89a842ad5cb2568e39d81225a329945c4da44e848c91' 
> 
> cmd=slim state=image.inspection.done
> 
> cmd=slim state=container.inspection.start
> 
> time="2024-12-31T13:23:55Z" level=error msg="dockerutil.BuildEmptyImage: dockerapi.BuildImage() error = API error (400): client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version\n / output: "
> 
> time="2024-12-31T13:23:55Z" level=fatal msg="slim: failure" error="API error (400): client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version\n" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:26 +0x5e\[ngithub.com/mintoolkit/mint/pkg/util/errutil.FailOn](http://ngithub.com/mintoolkit/mint/pkg/util/errutil.FailOn)({0x2f5b560, 0xc0006fa3a8})\n\[tgithub.com/mintoolkit/mint/pkg/util/errutil/errutil.go:32](http://tgithub.com/mintoolkit/mint/pkg/util/errutil/errutil.go:32) +0x4b\[ngithub.com/mintoolkit/mint/pkg/app/master/inspectors/container.(*Inspector](http://ngithub.com/mintoolkit/mint/pkg/app/master/inspectors/container.(*Inspector)).RunContainer(0xc0007b2608)\n\[tgithub.com/mintoolkit/mint/pkg/app/master/inspectors/container/container_inspector.go:439](http://tgithub.com/mintoolkit/mint/pkg/app/master/inspectors/container/container_inspector.go:439) +0x757\[ngithub.com/mintoolkit/mint/pkg/app/master/command/build.OnCommand](http://ngithub.com/mintoolkit/mint/pkg/app/master/command/build.OnCommand)(_, _, {_, _}, _, {_, _}, {_, _}, {0x0, ...}, ...)\n\[tgithub.com/mintoolkit/mint/pkg/app/master/command/build/handler.go:1141](http://tgithub.com/mintoolkit/mint/pkg/app/master/command/build/handler.go:1141) +0x4575\[ngithub.com/mintoolkit/mint/pkg/app/master/command/build.init.func1(0xc0002c5000)\n\tgithub.com/mintoolkit/mint/pkg/app/master/command/build/cli.go:780](http://ngithub.com/mintoolkit/mint/pkg/app/master/command/build.init.func1(0xc0002c5000)/n/tgithub.com/mintoolkit/mint/pkg/app/master/command/build/cli.go:780) +0x5cb0\[ngithub.com/urfave/cli/v2.(*Command](http://ngithub.com/urfave/cli/v2.(*Command)).Run(0x4685dc0, 0xc0002c5000, {0xc0008846f0, 0x3, 0x3})\n\[tgithub.com/urfave/cli/v2@v2.27.1/command.go:279](http://tgithub.com/urfave/cli/v2@v2.27.1/command.go:279) +0x7e2\[ngithub.com/urfave/cli/v2.(*Command](http://ngithub.com/urfave/cli/v2.(*Command)).Run(0xc00080c2c0, 0xc0002c4980, {0xc0000500a0, 0x5, 0x5})\n\[tgithub.com/urfave/cli/v2@v2.27.1/command.go:272](http://tgithub.com/urfave/cli/v2@v2.27.1/command.go:272) +0xa65\[ngithub.com/urfave/cli/v2.(*App](http://ngithub.com/urfave/cli/v2.(*App)).RunContext(0xc000391400, {0x2f85598, 0x4705340}, {0xc0000500a0, 0x5, 0x5})\n\[tgithub.com/urfave/cli/v2@v2.27.1/app.go:337](http://tgithub.com/urfave/cli/v2@v2.27.1/app.go:337) +0x58b\[ngithub.com/urfave/cli/v2.(*App](http://ngithub.com/urfave/cli/v2.(*App)).Run(...)\n\[tgithub.com/urfave/cli/v2@v2.27.1/app.go:311\ngithub.com/mintoolkit/mint/pkg/app/master.Run()\n\tgithub.com/mintoolkit/mint/pkg/app/master/app.go:15](http://tgithub.com/urfave/cli/v2@v2.27.1/app.go:311/ngithub.com/mintoolkit/mint/pkg/app/master.Run()/n/tgithub.com/mintoolkit/mint/pkg/app/master/app.go:15) +0x45\nmain.main()\n\[tgithub.com/mintoolkit/mint/cmd/mint/main.go:15](http://tgithub.com/mintoolkit/mint/cmd/mint/main.go:15) +0x187\n" version="linux/amd64|Aurora|1.41.7|a2a53d2348aeedf0d650d47debf477a2cad47111|2024-09-25_03:07:42PM"
> ```
> 
> Should I create an issue in the `mint` repository?

You can create an issue there as well, but it's optional only if you want to :-)

**Comment by jimcottrell** [comment]
I'll note that the [BitBucket Pipelines Runtime v3](https://support.atlassian.com/bitbucket-cloud/docs/enable-and-use-runtime-v3/) allows privileged Docker access without needing to run Docker-in-Docker, and I was able to run v1.41.8 successfully in a pipeline, but I still had to manually set an environment variable with the API version (with a newer version than before)

```
export DOCKER_API_VERSION='1.44'
```

**Comment by zandercodes** [comment]
Same issue
```
root@fsn1 ~ # docker version
Client: Docker Engine - Community
 Version:           29.2.1
 API version:       1.44 (downgraded from 1.53)
 Go version:        go1.25.6
 Git commit:        a5c7197
 Built:             Mon Feb  2 17:17:31 2026
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.2.1
  API version:      1.53 (minimum version 1.44)
  Go version:       go1.25.6
  Git commit:       6bc6209
  Built:            Mon Feb  2 17:17:31 2026
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v2.2.1
  GitCommit:        dea7da592f5d1d2b7755e3a161be07f43fad8f75
 runc:
  Version:          1.3.4
  GitCommit:        v1.3.4-0-gd6d73eb8
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@fsn1 ~ # export DOCKER_API_VERSION='1.44'
root@fsn1 ~ # docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/slim
>>> xray --target
time="2026-06-10T11:47:05Z" level=error msg="dockerutil.ListImages(): dockerapi.ListImages() error = API error (400): client version 1.24 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version"
time="2026-06-10T11:47:05Z" level=error msg="CompleteImage(\"\"): error - API error (400): client version 1.24 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version"
```

**Comment by kcq** [comment]
@zandercodes the `dslim/slim` container version is older, which explains the API version message. Try using the newer image `mintoolkit/mint` or `mintoolkit/mint-arm` for ARM64 machines. You can find the binary versions in the [most recent release here](https://github.com/mintoolkit/mint/releases/tag/1.41.8)
