### ISSUE TITLE
After slimming down, many environments are gone and the operation fails.

### ISSUE THREAD

**Issue by goldwater668** [slimtoolkit/slim#686]
docker-slim build --http-probe=false lui_label:v1

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/paddle/server_fast.py", line 7, in <module>
    from model_infer import text_cls
  File "/paddle/model_infer.py", line 5, in <module>
    from fast_uie import LUI_UIE
  File "/paddle/fast_uie.py", line 4, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils'

**Comment by hcymysql** [comment]
Hahaha, it's all the same.
