### ISSUE TITLE
Normally crop the size of the image

### ISSUE THREAD

**Issue by bilbilmyc** [slimtoolkit/slim#710]
Expected Behavior
=================

Normally crop the size of the image

---
Actual Behavior
```bash
>>> xray --target   suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-20240820090911:20240820090911
cmd=xray state=started
cmd=xray info=params target='suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-20240820090911:20240820090911' add-image-manifest='false' add-image-config='false' rm-file-artifacts='false'
cmd=xray state=image.api.inspection.start
cmd=xray info=image id='sha256:267d8364f21064ce3dd677211ea44269ed9f8d24d1d5850a07bdf1f06cfd5a48' size.bytes='71909010231' size.human='72 GB' architecture='amd64'
cmd=xray info=image.stack instructions='123' message='see report file for details' index='0' name='suzhou.harbor.com/new/cuda-devel:cuda12.1.0-ubuntu22.04-py3.10' id='sha256:f7e32ad98f3ff838d6d49a822bf0f26557ef2d8511d5242c15a710885c3ae083'
cmd=xray info=image.stack index='1' name='suzhou.harbor.com/new/aiguoliuguo-ingenious-parfait-1292-20240819205601:20240819205601' id='sha256:5322163c8e226dfdd88f1e32fccde04237712cd268d46fe3df048fb7080f8d96' instructions='1' message='see report file for details'
cmd=xray info=image.stack message='see report file for details' index='2' name='suzhou.harbor.com/new/aiguoliuguo-ingenious-parfait-1292-20240820002149:20240820002149' id='sha256:47077e9d52d5d4d616cdcbaf9daf8adadcf0c61cf3e0c6806f8a61094ef5fe6a' instructions='1'
cmd=xray info=image.stack index='3' name='suzhou.harbor.com/new/aiguoliuguo-ingenious-parfait-1292-20240820012734:20240820012734' id='sha256:e1082531eb596f753a202c370929d8f2cedecc235a7b62ac6a5965c8cb2489c2' instructions='1' message='see report file for details'
cmd=xray info=image.stack index='4' name='suzhou.harbor.com/new/aiguoliuguo-proud-rapture-5507-20240820040654:20240820040654' id='sha256:b37f8c7d65e7828e241762e8d094a86a8649aff28a97e0bc4bc86d6d474c545e' instructions='2' message='see report file for details'
cmd=xray info=image.stack name='suzhou.harbor.com/new/aiguoliuguo-proud-rapture-5507-20240820040953:20240820040953' id='sha256:beae9734e2ce812d40123fe7982e65eef8b679ffc458219d98a41f17eadadb44' instructions='1' message='see report file for details' index='5'
cmd=xray info=image.stack name='suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-aiguoliuguo-local_image:20240820041800' id='sha256:e28d118fc4c9c16086df633170f614384cf66a5222db92b4fc5babe5a5a1ef94' instructions='1' message='see report file for details' index='6'
cmd=xray info=image.stack message='see report file for details' index='7' name='suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-20240820043108:20240820043108' id='sha256:780681bf2da1e1ff744b33a98edf0ef29c0429efaad9c97396fc6b21094ef4fc' instructions='1'
cmd=xray info=image.stack name='suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-20240820085604:20240820085604' id='sha256:a9301704ecb31eb66c7ef27c461cfaaedc10d3fd0c37dc22beef7d8ea043ab27' instructions='1' message='see report file for details' index='8'
cmd=xray info=image.stack index='9' name='suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-aiguoliuguo-local_image:20240820090220' id='sha256:8dd83118599709d9a7b546ffbf7180b6fa860c94af96b10175283b073d741743' instructions='1' message='see report file for details'
cmd=xray info=image.stack instructions='1' message='see report file for details' index='10' name='suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-20240820090429:20240820090429' id='sha256:717cb0c2b75f5948076c120293472350ccd8334a1bc8271b60989f5266d48972'
cmd=xray info=image.stack id='sha256:267d8364f21064ce3dd677211ea44269ed9f8d24d1d5850a07bdf1f06cfd5a48' instructions='1' message='see report file for details' index='11' name='suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-20240820090911:20240820090911'
cmd=xray state=image.api.inspection.done
cmd=xray state=image.data.inspection.start
cmd=xray info=image.data.inspection.save.image.start

cmd=xray info=image.data.inspection.save.image.end
cmd=xray info=image.data.inspection.process.image.start
cmd=xray info=image.data.inspection.process.image.end
cmd=xray state=image.data.inspection.done
cmd=xray info=image.package.details
cmd=xray info=layers.count value='57'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xad6296]

goroutine 1 [running]:
github.com/slimtoolkit/slim/pkg/sysidentity.NewReportFromData(0xc000408000)
	github.com/slimtoolkit/slim/pkg/sysidentity/sysidentity.go:147 +0x5d6
github.com/slimtoolkit/slim/pkg/docker/dockerimage.(*Package).ProcessIdentityData(0xc0007b2510?)
	github.com/slimtoolkit/slim/pkg/docker/dockerimage/dockerimage.go:1405 +0x1f
github.com/slimtoolkit/slim/pkg/app/master/command/xray.printImagePackage(0xc0007b24c8, 0xc00048bd40, {0x0?, 0x0?}, {0x0?, 0x0?}, 0x0?, 0x0?, 0xc00067a420, 0xffffffffffffffff, ...)
	github.com/slimtoolkit/slim/pkg/app/master/command/xray/handler.go:683 +0x25d
github.com/slimtoolkit/slim/pkg/app/master/command/xray.OnCommand(0xc0007b24c8, 0xc0001465a0, 0xc0007b24e8, {_, _}, _, {_, _}, {0x0, 0x0}, ...)
	github.com/slimtoolkit/slim/pkg/app/master/command/xray/handler.go:521 +0x32c8
github.com/slimtoolkit/slim/pkg/app/master/command/xray.glob..func1(0xc000406cc0)
	github.com/slimtoolkit/slim/pkg/app/master/command/xray/cli.go:337 +0x1d98
github.com/urfave/cli/v2.(*Command).Run(0x33a8f00, 0xc000406cc0, {0xc00067a2a0, 0x3, 0x3})
	github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*Command).Run(0xc000564160, 0xc000406700, {0xc0004060c0, 0x4, 0x4})
	github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e
github.com/urfave/cli/v2.(*App).RunContext(0xc000414200, {0x23470c8?, 0x341e0a0}, {0xc0004060c0, 0x4, 0x4})
	github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.27.1/app.go:311
github.com/slimtoolkit/slim/pkg/app/master/command.(*InteractiveApp).execute(0xc0004585d0, {0xc0006ce000?, 0x1?})
	github.com/slimtoolkit/slim/pkg/app/master/command/cliprompt.go:108 +0x37e
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000408280)
	github.com/c-bata/go-prompt@v0.2.3/prompt.go:85 +0x846
github.com/slimtoolkit/slim/pkg/app/master/command.(*InteractiveApp).Run(...)
	github.com/slimtoolkit/slim/pkg/app/master/command/cliprompt.go:273
github.com/slimtoolkit/slim/pkg/app/master.newCLI.func4(0xc000406140?)
	github.com/slimtoolkit/slim/pkg/app/master/cli.go:187 +0x45
github.com/urfave/cli/v2.(*Command).Run(0xc00045c160, 0xc000406140, {0xc0000500a0, 0x1, 0x1})
	github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*App).RunContext(0xc000414200, {0x23470c8?, 0x341e0a0}, {0xc0000500a0, 0x1, 0x1})
	github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.27.1/app.go:311
github.com/slimtoolkit/slim/pkg/app/master.Run()
	github.com/slimtoolkit/slim/pkg/app/master/app.go:15 +0x45
main.main()
	github.com/slimtoolkit/slim/cmd/slim/main.go:15 +0x187
```
=================
![image](https://github.com/user-attachments/assets/a5295967-91e2-435b-af09-8a41f1fa415b)

![image](https://github.com/user-attachments/assets/beb50a22-1af2-4be5-97eb-b6b1d4428990)

---
Steps to Reproduce the Problem
===============================
 

  1.
  1.
  1.

---
Specifications
=================
  - Version:
  - Platform:

**Comment by bilbilmyc** [comment]
```bash
[root@g007 dist_linux]# docker images | grep "aiguoliuguo-generous" | grep 20240820090911
suzhou.harbor.com/new/aiguoliuguo-generous-marine-6381-20240820090911                    20240820090911                              267d8364f210        About an hour ago   71.9GB
```

**Comment by kcq** [comment]
Thanks for the bug report @bilbilmyc ! This will be fixed in the upcoming release (happening soon). I'll post a follow up when it's available.

**Comment by kcq** [comment]
@bilbilmyc try the [latest release](https://github.com/mintoolkit/mint/releases/tag/1.41.6) to see if you still have any problems there

**Comment by bilbilmyc** [comment]
Ok, I'll use the [latest release](https://github.com/mintoolkit/mint/releases/tag/1.41.6)  for testing
