### ISSUE TITLE
Nil pointer dereference in xray/handler.go:1004 (linux.amd64 v1.40.11)

### ISSUE THREAD

**Issue by bitplane** [slimtoolkit/slim#741]
# 🔍 Details

Crash in [master/command/xray/handler.go](https://github.com/slimtoolkit/slim/blob/1.40.11/pkg/app/master/command/xray/handler.go#L1004), line 1004

Command run: `xray --target bitplane1/uh-halp-data-binaries:ubuntu-500-x86_64`

* [📺 asciinema recording](https://asciinema.org/a/7ShQVnEcyn8GNIoNOlonwzEMo)

Stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x1a9b32a]

goroutine 1 [running]:
github.com/slimtoolkit/slim/pkg/app/master/command/xray.printImagePackage(0xc0006624c8, 0xc000641520, {0x0?, 0x0?}, {0x0?, 0x0?}, 0x0?, 0x0?, 0xc000612420, 0xffffffffffffffff, ...)
        github.com/slimtoolkit/slim/pkg/app/master/command/xray/handler.go:1004 +0x6c6a
github.com/slimtoolkit/slim/pkg/app/master/command/xray.OnCommand(0xc0006624c8, 0xc00061c3f0, 0xc0006624e8, {_, _}, _, {_, _}, {0x0, 0x0}, ...)
        github.com/slimtoolkit/slim/pkg/app/master/command/xray/handler.go:521 +0x32c8
github.com/slimtoolkit/slim/pkg/app/master/command/xray.glob..func1(0xc000694cc0)
        github.com/slimtoolkit/slim/pkg/app/master/command/xray/cli.go:337 +0x1d98
github.com/urfave/cli/v2.(*Command).Run(0x33a8f00, 0xc000694cc0, {0xc0006122a0, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*Command).Run(0xc000478420, 0xc000694740, {0xc000694680, 0x4, 0x4})
        github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e
github.com/urfave/cli/v2.(*App).RunContext(0xc00025c200, {0x23470c8?, 0x341e0a0}, {0xc000694680, 0x4, 0x4})
        github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.27.1/app.go:311
github.com/slimtoolkit/slim/pkg/app/master/command.(*InteractiveApp).execute(0xc0006a2600, {0xc000a08140?, 0x1?})
        github.com/slimtoolkit/slim/pkg/app/master/command/cliprompt.go:108 +0x37e
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000696200)
        github.com/c-bata/go-prompt@v0.2.3/prompt.go:85 +0x846
github.com/slimtoolkit/slim/pkg/app/master/command.(*InteractiveApp).Run(...)
        github.com/slimtoolkit/slim/pkg/app/master/command/cliprompt.go:273
github.com/slimtoolkit/slim/pkg/app/master.newCLI.func4(0xc000694100?)
        github.com/slimtoolkit/slim/pkg/app/master/cli.go:187 +0x45
github.com/urfave/cli/v2.(*Command).Run(0xc000478160, 0xc000694100, {0xc0000500a0, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*App).RunContext(0xc00025c200, {0x23470c8?, 0x341e0a0}, {0xc0000500a0, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.27.1/app.go:311
github.com/slimtoolkit/slim/pkg/app/master.Run()
        github.com/slimtoolkit/slim/pkg/app/master/app.go:15 +0x45
main.main()
        github.com/slimtoolkit/slim/cmd/slim/main.go:15 +0x187
```
---

# 👣 Steps

```shell
$ docker pull bitplane1/uh-halp-data-binaries:ubuntu-500-x86_64
$ slim
>>> xray --target bitplane1/uh-halp-data-binaries:ubuntu-500-x86_64
```
---

# 🕶️ Specs

```
$ slim --version
slim version linux/amd64|Transformer|1.40.11|1b271555882eacdfb4e6598d6d0552e9b9b1449b|2024-02-02_01:36:22PM
```

**Comment by kcq** [comment]
Thank you for the detailed report @bitplane ! This will be straight forward to prevent. A new release is coming in the next few days (will be [here](https://github.com/mintoolkit/mint)) and I'll post a release link in this issue.

**Comment by bitplane** [comment]
If you're looking for a stress test case, the same repo has 200GB Ubuntu repos for `x86_64` and `aarch64`, with as many packages as I could manage to install (well, all the ones that contain binaries that someone might type into a command line).

Source repo is [here](https://github.com/bitplane/uh-halp-data), if it's the sort of thing you'd find useful :)

**Comment by kcq** [comment]
> If you're looking for a stress test case, the same repo has 200GB Ubuntu repos for `x86_64` and `aarch64`, with as many packages as I could manage to install (well, all the ones that contain binaries that someone might type into a command line).
> 
> Source repo is [here](https://github.com/bitplane/uh-halp-data), if it's the sort of thing you'd find useful :)

This is very cool! Thank you @bitplane

**Comment by kcq** [comment]
Try the `x.1.42.2` version from [here](https://github.com/mintoolkit/mint/releases/tag/1.41.7). It's a temporary release, but it might do a better job with your image (it's a pretty big image :-))
